### ISSUE TITLE
How to use self train result? 

### ISSUE THREAD

**Issue by makcedward** [allenai/bilm-tf#100]
First of all, thank you very much for this brilliant architecture. 

I tried to load pre-trained embeddings layer from TF hub and it works great. After that, I tried to train a model by myself. So I follow "Training a biLM on a new corpus" step to train bilm by giving vocab and other files. After executing 
`python bin/dump_weights.py --save_dir=/output_path/to/checkpoint --outfile=/output_path/to/weights.hdf5`

May you suggest how can I use this result in Tensorflow/ Keras?

**Comment by matt-peters** [comment]
You can use those weights with the remainder of the code, see:

https://github.com/allenai/bilm-tf/blob/master/README.md#using-pre-trained-models
