### ISSUE TITLE
Task specific trainable parameters

### ISSUE THREAD

**Issue by mathetes87** [allenai/bilm-tf#101]
Hi, I have a question regarding the layer weights and the gamma parameter that the paper states as fundamental to achieve good results in downstream tasks.

If I understand correctly there are 2 macro steps to use ELMo correctly.

1. Task agnostic: We train the biLM with lots of unlabelled data in a language modelling manner.
2. Task specific: 
a) Finetune: Once we have our biLM model fully trained, we can finetune our model to the specific task at hand (say text classification for medical domain) an achieve much better results with a single pass of the data.
b) **Actually use ELMo, and my actual question**: In order to finally use ELMo embeddings we need to train the weights to average the token representation and the layers, along with a gamma parameter. 

The *elmo.py* file seems to output the embeddings already weighted, but how can this be since the scripts have not necessarily seen the task specific data yet? The same goes for the gamma value.

Thanks

**Comment by mathetes87** [comment]
In issue #48 this is partially answered, but I still don't understand how the weights are learned even though the model has never seen the task specific data...

**Comment by matt-peters** [comment]
The function `weight_layers` uses `tf.get_variable` to introduce trainable parameters:

https://github.com/allenai/bilm-tf/blob/master/bilm/elmo.py#L68

Then when you use the returned `weighted_op` in your model, those parameters are optimized along with the rest of your model parameters.

**Comment by mathetes87** [comment]
Perfect. Thanks a lot!

**Comment by guotong1988** [comment]
Thank you very much.
