### ISSUE TITLE
Can you share the "Pre-trained ELMo Models(elmo_2x1024_128_2048cnn_1xhighway)" checkpoint

### ISSUE THREAD

**Issue by kbzhang** [allenai/bilm-tf#105]
I want to fine tune the existing weights(elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5) on new data, but your shared checkpoint model is "elmo_2x4096_512_2048cnn_2xhighway", can you share this checkpoint model?
Thanks.

**Comment by matt-peters** [comment]
Here are the file, same vocabulary file as the 2x4096-512 model.


https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/tf_checkpoint/checkpoint

https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/tf_checkpoint/model.ckpt-1501260.data-00000-of-00001

https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/tf_checkpoint/model.ckpt-1501260.index

https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/tf_checkpoint/model.ckpt-1501260.meta

https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/tf_checkpoint/options.json

**Comment by helboukkouri** [comment]
Hi @matt-peters,
Could you also provide the checkpoint for the model trained on PubMed ?
Thanks a lot :)
