### ISSUE TITLE
PyTorch implementation?

### ISSUE THREAD

**Issue by Andy-jqa** [allenai/bilm-tf#109]
Hi,

Do you have the biLM codes in PyTorch? The readme says you have PyTorch implementations, but that points back to the allennlp homepage.

Thanks a lot,
Andy

**Comment by matt-peters** [comment]
See: https://allennlp.org/elmo
and https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md

Training isn't yet supported but will be soon.

**Comment by pzhang84** [comment]
Hi @matt-peters, I wonder if training ELMo is supported in PyTorch version now?
