### ISSUE TITLE
Why the embeddings for each sentence are a shape (3, n_tokens, 1024) ?

### ISSUE THREAD

**Issue by guotong1988** [allenai/bilm-tf#115]
What does 3 means?
Thank you very much.

**Comment by guotong1988** [comment]
embedding,
forward LSTM,
backward LSTM,
?

**Comment by yaoyao2** [comment]
What does 3 means? I‘m also very curious about this question.

**Comment by nlpjoe** [comment]
token representation and two layer of bi-lstm output, I guess.

**Comment by nlpjoe** [comment]
#19
