### ISSUE TITLE
 After training is completed，how to use elmo embedding for specific task，etc classificationtask

### ISSUE THREAD

**Issue by Pydataman** [allenai/bilm-tf#116]

**Comment by nreimers** [comment]
The natural choice would be to use it in the AllenNLP framework. There, they provide many different architectures for various tasks.

But you can also use it with Tensorflow or keras. How to use it with keras, have a look at my repository:
https://github.com/UKPLab/elmo-bilstm-cnn-crf

The repository implements an ELMo-BiLSTM-CNN-CRF model, that can be used for sequence tagging tasks like NER.

I also added an example how to use it with Keras for sentence classification:
https://github.com/UKPLab/elmo-bilstm-cnn-crf/blob/master/Keras_ELMo_Tutorial.ipynb
