### ISSUE TITLE
How should the "many" training files be split?

### ISSUE THREAD

**Issue by PhilipMay** [allenai/bilm-tf#117]
Hi. In the readme you say that the training data should be split into many files.
Is it important how they are split?
Do they all have to contain the same number of tokens or sentences?
Thanks.

**Comment by matt-peters** [comment]
It's important to randomly split your sentences / paragraphs / etc across the training files in order to ensure training processes your data randomly.  They don't need to contain the same number of tokens but you will see reduced memory pressure if they are approximately equally sized.

**Comment by PhilipMay** [comment]
Ok thanks. I did just split them all with 500,000 lines. With linux split command.
