### ISSUE TITLE
The vocabulary in training and testing

### ISSUE THREAD

**Issue by FynnYoung** [allenai/bilm-tf#120]
Hi,
Suppose I have pre-trained an ELMo model with a large corpus and its corresponding vocabulary, and next I want to run usage_cached.py to dump the embeddings of a new and small dataset. 
My question is that, during dumping, should I use the vocabulary of the original large corpus, or just build a small vocabulary of the new dataset?

**Comment by matt-peters** [comment]
You can use a smaller vocabulary for the new dataset, assuming it includes all of the unique tokens in that dataset.
