### ISSUE TITLE
Final hidden states in bidirectional LM

### ISSUE THREAD

**Issue by JJAlmagro** [allenai/bilm-tf#123]
Hello

Could you explain how the script transfers the final hidden states as the initial hidden states of the next batch when using the bidirectional model? The process makes sense when just training in the forward direction, but when training both directions, how does it get the final state of the backward direction?

**Comment by matt-peters** [comment]
This is the op that updates the hidden states after each batch, you can trace the logic backward from here: https://github.com/allenai/bilm-tf/blob/master/bilm/model.py#L600
