### ISSUE TITLE
Separating Embeddings for NER

### ISSUE THREAD

**Issue by jeniyat** [allenai/bilm-tf#124]
Is it possible to use the character embedding only(I want to exclude word embedding and context embedding) for NER task?

**Comment by matt-peters** [comment]
Yes it is possible to representations from any of the layers. If you just want the character CNN + highway layers then you can use this function: https://github.com/allenai/bilm-tf/blob/master/bilm/model.py#L603 to write them to a file for a given vocabulary file.

**Comment by jeniyat** [comment]
Thanks for your response. I want to do a feature ablation study for the three types of embedding generated by elmo. I am training elmo on a new dataset. I  want to check the impact of word embedding, character embedding and context embeding separately. 
I think https://github.com/allenai/bilm-tf/blob/master/bilm/model.py#L603  will give the character embedding (Thanks for the link)
How to extract the word and context embedding?
