### ISSUE TITLE
occurs error when integrating tensorflow hub  mode of ELMO to my graph

### ISSUE THREAD

**Issue by zjh-nudger** [allenai/bilm-tf#125]
the core information:
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'inference/module_apply_tokens/map/while/Merge' has inputs from different frames. The input 'inference/module_apply_tokens/map/while/Enter' is in frame 'inference/module_apply_tokens/map/while/while_context'. The input 'global_step/add' is in frame ''.

how can I solve it. thanks

**Comment by matt-peters** [comment]
I suggest opening an issue on the tensorflow hub repository.
