### ISSUE TITLE
Using the hdf5 for a classification task

### ISSUE THREAD

**Issue by sandhiya18** [allenai/bilm-tf#131]
How do I use the .hdf5 weight file created from bin/dump_weights.py for a Text Classification problem?

**Comment by matt-peters** [comment]
You can find an implementation of our state-of-the-art sentiment classification model (described in the paper) in allennlp, see the bottom row of this table (labeled SST-5: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#reproducing-the-results-from-deep-contextualized-word-representations)
