### ISSUE TITLE
doubt about weight dumping

### ISSUE THREAD

**Issue by yinnxinn** [allenai/bilm-tf#134]
the source code in model.py in restore the model . 
`    if varname_in_file == 'embedding':

        with h5py.File(embedding_weight_file, 'r') as fin:

            # Have added a special 0 index for padding not present
            # in the original model.
            embed_weights = fin[varname_in_file][...]
            weights = np.zeros(
                (embed_weights.shape[0] + 1, embed_weights.shape[1]),
                dtype=DTYPE
            )
            weights[1:, :] = embed_weights`
I have doubt about the +1 operation. In the train stage , the data we feed into the graph is 
`   inputs = np.zeros([batch_size, num_steps], np.int32) `

   ` targets = np.zeros([batch_size, num_steps], np.int32)`

 I think there's ZERO in the embedding . In addtion , in the dictionary file , the item index should start from 1 and the 0 reserved for the padding .

how do you think?

**Comment by matt-peters** [comment]
For prediction, padding spaces are indicated with the `0` id.  The dictionary file doesn't include a padding token, but it is handled elsewhere.  See https://github.com/allenai/bilm-tf#whats-the-deal-with-n_characters-and-padding
