### ISSUE TITLE
GPU usage problem when training

### ISSUE THREAD

**Issue by NotToday** [allenai/bilm-tf#140]
When training on new corpus, I used three gpus. While training, the video memories of the cards were all occupied, but one of the video card has usage of 0% all the time. How to solve the problem?

**Comment by PhilipMay** [comment]
Did you set this here: https://github.com/allenai/bilm-tf/blob/master/bin/train_elmo.py#L16 ?

**Comment by NotToday** [comment]
> Did you set this here: https://github.com/allenai/bilm-tf/blob/master/bin/train_elmo.py#L16 ?

**Comment by NotToday** [comment]
> Did you set this here: https://github.com/allenai/bilm-tf/blob/master/bin/train_elmo.py#L16 ?

You are right. I set CUDA_VISIBLE_DEVICES and forget to reset the n_gpu. Thanks~

**Comment by PhilipMay** [comment]
:-)
