### ISSUE TITLE
Question: Using GPUs for allennlp.modules.elmo.Elmo class

### ISSUE THREAD

**Issue by rosequ** [allenai/bilm-tf#141]
Hi, I tried the features from both `allennlp.modules.elmo.Elmo` and `allennlp.commands.elmo.ElmoEmbedder`.  The features obtained from `allennlp.modules.elmo.Elmo`  worked the best for our models (although it's computationally expensive). ElmoEmbedder takes `cuda_device` as an argument. Is there something similar that I can do to run `allennlp.modules.elmo.Elmo` on GPU?

**Comment by matt-peters** [comment]
This should really be opened in the `allennlp` repo.  `allennlp.modules.elmo.Elmo` is a `torch.nn.Module` submodule, so just use the default `.cuda(device)` method to move to GPU.
