### ISSUE TITLE
unroll_steps and maximum number of tokens per sequence

### ISSUE THREAD

**Issue by agemagician** [allenai/bilm-tf#142]
As written in the readme that the model uses fixed size of 20 tokens.
Does it mean if I have a sequence of 100 token, the model is going to divide it to 5 training samples ?

If yes, is not that will make the algorithm loose information, if the tokens in this sequence depend on each other to provide a correct meaning ?

**Comment by matt-peters** [comment]
Yes, it splits into 5 different batches.  The LSTM states are carried over from batch to batch, but back propagation is only performed with the batch.

**Comment by agemagician** [comment]
In this case, if our sequence "sentence" length is on average 1024 tokens.

Do we have to make the unroll_steps much bigger than 20 because the back propagation is only performed with the batch, or since the LSTM states are carried we don't have to change it ?

**Comment by matt-peters** [comment]
If you want to train long contexts, then yes you will see some benefits if you increase unroll steps.  You will also need to decrease the batch size accordingly (the total number of tokens in a batch is equal to batch_size * unroll_steps).  Each line in your input file is treated independently, so when preparing your data make each line one long 1024 token length context.

**Comment by xuyong3250** [comment]
> Yes, it splits into 5 different batches. The LSTM states are carried over from batch to batch, but back propagation is only performed with the batch.

I read the code in data.py, It seems that if a sentence is longer than num_steps, the remained part will be put in cur_steam[i], this variable will not be used in the next iteration. In other words, sentence longer than num_steps will be truncated.
