### ISSUE TITLE
Cannot dump embeddings of hdf5

### ISSUE THREAD

**Issue by enod** [allenai/bilm-tf#144]
As guide suggested, 

> Important: always set n_characters to 262 after training (see below).

But when I set n_characters to 262 and run 
```
python bin/dump_weights.py \
    --save_dir /output_path/to/checkpoint
    --outfile /output_path/to/weights.hdf5
```
It gives:
`bilm.data.InvalidNumberOfCharacters: Set n_characters=261 for training see the README.md`

But it works when n_characters set to 262. Am I doing something wrong here?

**Comment by matt-peters** [comment]
Keep n_characters=261 when generating the weight file, but change to 262 when using the weights for prediction.
