### ISSUE TITLE
How to calculate perplexity for test dataset? I need accurate ppl for each sentence in my test file.

### ISSUE THREAD

**Issue by gai1995** [allenai/bilm-tf#146]
Hello, thanks for your contribution first!
So far, I have trained my own elmo guided by your readme file. Because of my trainingset is Chinese-based (your code could not read Chinese, so I converted each word into 'a123' like this), so I just used the token_input and removed char_cnn related settings in options. 
The training process seems working well, but I'm trying to 1) calculate the ppl of each sentence in my test set, but now I could only get the batch_ppl and average ones (honestly I'm not very clear about that in test). 2) I want to obtain the word embedding of my test sentences from trained model, I tried to use dump_xxx_embedding to do so, but I examined the source code, which requires char_cnn input (I used to set the char_input as False, but another error occurred). 

Could you please give me some advice or guidance? Thank you very much!!

**Comment by matt-peters** [comment]
See: https://github.com/allenai/bilm-tf/issues/137
