### ISSUE TITLE
Question:Could I fine-tune the language model by classification task on another dataset?

### ISSUE THREAD

**Issue by gai1995** [allenai/bilm-tf#148]
I want to fine-tune the ELMo on a classification task and hope the parameters could change during the task. Could you give me some hints where to modify the code to suit the fine-tune training? I'm trying to modify the 'build_loss' in training.py, but stuck with how to feed my original sentence and class label...

Thanks!

**Comment by matt-peters** [comment]
Yes it is certainly possible to fine tune the model.   To feed in your original sentence use the existing code in `data.py` to convert the words to sequences of character ids.  You will need to write some additional code to convert your class label to ids.
