### ISSUE TITLE
How to pre-compute ELMo representations and use in other frameworks?

### ISSUE THREAD

**Issue by ghost** [allenai/bilm-tf#153]
Hi, 
I have a working classification model for named entity recognition, which works with Glove and word2vec embeddings. Now I want to pre-compute ELMo embeddings and use them as input for my baseline model. But I can't seem to figure how I can do that. Any help is appreciated.
Thanks

**Comment by PhilipMay** [comment]
You should have a look into:

- usage_cached.py
- usage_character.py
- usage_token.py
