### ISSUE TITLE
An issue when trying to dump the weights

### ISSUE THREAD

**Issue by RytisKumpa** [allenai/bilm-tf#156]
Hi,

When I try to dump the weights, I get this error: "bilm.data.InvalidNumberOfCharacters: Set n_characters=261 for training see the README.md"
If I understand correctly, I have to set n_characters to 262 when dumping the weights. Any help would be appreciated. Thanks!

**Comment by Rusiecki** [comment]
Hey what was the solution for this problme?

**Comment by hichiaty** [comment]
I have the same issue, have you managed to fix it?

**Comment by ssubraveti** [comment]
I'm running into the same issue... @RytisKumpa what did you do to fix this?
