### ISSUE TITLE
Sentence longer than unroll_steps will be truncated.

### ISSUE THREAD

**Issue by xuyong3250** [allenai/bilm-tf#157]
I read the code in data.py. In the function "__get_batch()", it seems that if a sentence is longer than num_steps, the remained part will be put in cur_steam[i], then the inner iteration will stop. The variable cur_stream[i] will not be used in the next iteration. In other words, sentence longer than num_steps will be truncated. Is this a bug or a feature?

**Comment by agemagician** [comment]
This is strange because I asked a similar question in:
https://github.com/allenai/bilm-tf/issues/142

As written in the readme that the model uses fixed size of 20 tokens.
Does it mean if I have a sequence of 100 token, the model is going to divide it to 5 training samples ?

and the answer was:

Yes, it splits into 5 different batches. The LSTM states are carried over from batch to batch, but back propagation is only performed with the batch.

@matt-peters  could you please give us your feedback here ?

**Comment by matt-peters** [comment]
The code will carry over un-used tokens to the next batch with the same index so that any sequence length is treated as a continuous sequence, but split into separate batches.  There is a correctness check here: https://github.com/allenai/bilm-tf/blob/master/tests/test_data.py#L202

**Comment by xuyong3250** [comment]
Thanks for your reply. The cur_steam[i] will be used in next batch. 

But it seems the sequence information in the long sentences will not be fullly used in a way. For example, given sentences
 

- ["You can write ELMo representations to disk with the elmo command","The elmo command will write all the biLM individual layer representations for a dataset of sentences to an HDF5 file"]

we set batch_size=2,unroll_steps=4. Then the token batches we get will be

-  [[bos,"you","can","write",eos],[bos,"The","elmo","command",eos]]
-  [[bos,"elmo","representation","to",eos],[bos,"will","write","all",eos]].
- ...
 
Some sequence information will loss. Actually this loss will be small if we set unroll_steps large enough.

> The code will carry over un-used tokens to the next batch with the same index so that any sequence length is treated as a continuous sequence, but split into separate batches. There is a correctness check here: https://github.com/allenai/bilm-tf/blob/master/tests/test_data.py#L202

**Comment by xuyong3250** [comment]
> The code will carry over un-used tokens to the next batch with the same index so that any sequence length is treated as a continuous sequence, but split into separate batches. There is a correctness check here: https://github.com/allenai/bilm-tf/blob/master/tests/test_data.py#L202

Thanks for your reply. The cur_stream[i] will be used in next batch. 

I also look into the [issue](https://github.com/allenai/bilm-tf/issues/142). In your latest reply, "Each line in your input file is treated independently", Is this conclusion is based on the assumption that context is very long? Because if the sentence are very short, the adjacent lines in the input file will be treated as continuous sentences in the batch.

**Comment by matt-peters** [comment]
Adjacent lines in the file are treated independently, and the logic whether to train on individual sentences or longer contexts is pushed into the data preparation process (outside this repository).  For example, if you want to train on 5 consecutive sentences then concatenate groups of 5 sentences and output them as a single line in the training file.  If you want to train with entire document contexts then make each line in your training file be one single document.
