### ISSUE TITLE
Question - I have question regarding the part "where to include ELMo"

### ISSUE THREAD

**Issue by imgarylai** [allenai/bilm-tf#159]
Thank for your awesome work!

I have a question regarding the part "where to include ELMo" in section 5.2, Deep contextualized word representations. 

As it was mentioned in the paper, those tasks were experimented on including ELMo at both the input and output layers, instead of only including ELMo at the input layer. Would you please describe this more specifically? 

Here is my understanding, please let me know if I understand it correctly. So, including ELMo at the input layer means that ELMo is the encoder or perhaps part of encoder, right? And the representations generated by the encoder, ELMO, can be passed to the next layer/network. However, for the output part, I don't understand quietly. Does it mean that we include the representations from the encoder with the result from output layer, and combine these two together before the decoder. And the concatenation of representation and output from last layer is passed to the decoder.

**Comment by matt-peters** [comment]
In the experiments with two separate ELMo layers, the architecture in the encoder is:

ELMo with learned scalar weights -> BiLSTM -> BiLSTM output -> BiLSTM output concatenated to ELMo with separate learned scalar weights -> output layers.
