### ISSUE TITLE
Can I train a language model and generate weights file by myself？

### ISSUE THREAD

**Issue by crazyofapple** [allenai/bilm-tf#16]
Thank you !

**Comment by matt-peters** [comment]
Sorry, no we haven't released the training code.

**Comment by jackalhan** [comment]
In order to create ELMO embeddings for my own dataset, do I need to use the trained weights provided by the following link : https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5

Thank you

**Comment by matt-peters** [comment]
Yes, that is the weight file for the pre-trained biLM.  You will need the options file that specifies the hyperparameters.  These both linked from README.md.

**Comment by jackalhan** [comment]
Thank you. 
That is the weight file for the pre-trained biLM. I will use it with its options file like you mentioned in README.md. So in order to create ELMO embeddings for questions and paragraphs separately, which of your example files I need to follow?

**Comment by ngbrenda** [comment]
Can you provide more detailed instructions to train my own elmo embedding in your README? I want to train elmo on NYT and compare against word2vec or glove.
