### ISSUE TITLE
Releasing all TF checkout point of elmo?

### ISSUE THREAD

**Issue by GaryYufei** [allenai/bilm-tf#164]
Hi, Thanks for this great work.

I am wondering if we can have all the tf checkpoint file? (e.g., 5.5B elmo checkpoint?) so that people can use it for LM usage.

**Comment by ykiprov** [comment]
There is a checkpoint for download but it's in the FAQ section, probably you missed it?

https://github.com/allenai/bilm-tf#can-you-provide-the-tensorflow-checkpoint-from-training
