### ISSUE TITLE
Can't find a checkpoint for "Medium" ELMo (2x2048_256)

### ISSUE THREAD

**Issue by helboukkouri** [allenai/bilm-tf#172]
Hi,

I want to fine-tune the "medium" ELMo model on some domain-specific data. I managed to find links for both the "small" and "original" models ([here](https://github.com/allenai/bilm-tf/issues/105) and [here](https://github.com/allenai/bilm-tf)) but simply replacing the model names in either with **2x2048_256_2048cnn_2xhighway** doesn't work.

This is the exact error I get when trying to download using wget:
```
--2019-03-06 15:46:09--  https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x2048_256_2048cnn_1xhighway/tf_checkpoint/checkpoint
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.201.224
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.201.224|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-03-06 15:46:10 ERROR 403: Forbidden.
```

```
--2019-03-06 15:44:10--  https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x2048_256_2048cnn_2xhighway_tf_checkpoint/checkpoint
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.201.216
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.201.216|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-03-06 15:44:11 ERROR 403: Forbidden.
```

Am I using the wrong links or is the checkpoint for the "medium" model not public yet ?

Thanks in advance :)

**Comment by abaheti95** [comment]
Hi, could you provide the links to the checkpoint files for medium model? I am trying to fine-tune the medium model on a new dataset and trying to find the checkpoint and vocab files.

**Comment by abaheti95** [comment]
Hi @matt-peters,
Could you share the links to checkpoint of medium model as well. Simply changing the links in mentioned #105 gave "access denied" errors. Could you provide the correct checkpoint and vocab files links for this medium model?
