### ISSUE TITLE
Reproducing the Word Sense Disambiguation task

### ISSUE THREAD

**Issue by glnmario** [allenai/bilm-tf#183]
The [paper](https://arxiv.org/pdf/1802.05365.pdf) gives a partially ambiguous account of the WSD experiments. 

### Is there any code available to reproduce them?

--- 
Now, some more specific questions:
> Given a sentence, we can use the biLM representations to predict the sense of a target word using a simple 1-nearest neighbor approach, similar to Melamud et al. (2016). To do so, we first use the biLM to compute representations for all words in Sem-Cor 3.0, our training corpus (Miller et al., 1994), and then take the average representation for each sense.

Does this mean the following?

1. Load the pre-trained language model
2. For each word _type_ _w_ in Sem-Cor 3.0, for each WordNet sense of _w_, extract a contextualised representations for each occurrence in the corpus
3. For each word _type_ _w_ in Sem-Cor 3.0, and for each of the WordNet senses, use the average vector as a fixed word-sense-specific representation

> At test time, we again use the biLM to compute representations for a given target word and take the nearest neighbor sense from the training set...

I assume the nearest neighbour is chosen only among the representations for the corresponding lemma.

> ... falling back to the first sense from WordNet for lemmas not observed during training. 

This should be the _WordNet first sense_ baseline introduced by [Raganato et al. (p. 104)](https://www.aclweb.org/anthology/E17-1010). Do you know why this does not correspond to the first sense assigned by `nltk.corpus.wordnet`?

> Table 5 compares WSD results using the evaluation framework from Raganato et al. (2017b) across the same suite of four test sets in Raganato et al. (2017a).

The four test sets should be Senseval 2, Senseval 3, Semeval 2015, and Semeval 2017.

**Comment by matt-peters** [comment]
I don't have a clean, maintained version to reproduce the WSD results, but this will get you 95% of the way:

https://gist.github.com/matt-peters/58d6e09384638c31292f928a14da9a9c

The only missing step is writing out the embeddings from the SemCor dataset to a HDF5 file, which you can accomplish by modifying: https://github.com/allenai/bilm-tf/blob/master/usage_cached.py

Everything else in your question looks right at a glance, see the code for details.
