### ISSUE TITLE
Have you tested ELMo on Chinese?

### ISSUE THREAD

**Issue by shuizhonghaitong** [allenai/bilm-tf#187]
If you have conducted experiments on Chinese, how is the test perplexity?

**Comment by matt-peters** [comment]
I haven't run a Chinese only model, although others have.  Potentially relevant citations:

- Polyglot Contextual Representations Improve Crosslingual Transfer https://arxiv.org/pdf/1902.09697.pdf
- Pretrained ELMo for Many Languages: https://github.com/HIT-SCIR/ELMoForManyLangs
