### ISSUE TITLE
(n_sentences, 3, max_sentence_length, 1024)

### ISSUE THREAD

**Issue by rclover** [allenai/bilm-tf#19]
After running inference with the batch, the return biLM embeddings are a numpy array with shape (n_sentences, 3, max_sentence_length, 1024), after removing the special begin/end tokens.
I assume that "(n_sentences, 3, max_sentence_length, 1024)" should be "(n_sentences, max_sentence_length, 1024)"?

**Comment by matt-peters** [comment]
Our biLM code returns the activations from each layer of the network.  The pre-trained model provided has three layers: two biLSTM layers and the context insensitive token type layer.  As a result it returns size `(n_sentences, 3, max_sentence_length, 1024)` for each batch.
