### ISSUE TITLE
question: my trained model gives output dictionary with different fields from those from the tf.hub model

### ISSUE THREAD

**Issue by abd-ghreeb** [allenai/bilm-tf#193]
When using pre-trained models, I get an output dictionary different from the output dictionary explained in the published [tf.hub model](https://tfhub.dev/google/elmo/2) 
My output dictionary's signature is 
```
> model = BidirectionalLanguageModel(options_file, weight_file)
> ops = model(ids_placeholder)
> print (ops)
{'token_embeddings': <tf.Tensor 'bilm/Reshape_1:0' shape=(?, ?, 512) dtype=float32>, 
'lengths': <tf.Tensor 'sub:0' shape=(?,) dtype=int32>, 
'mask': <tf.Tensor 'Cast_1:0' shape=(?, ?) dtype=bool>, 
'lm_embeddings': <tf.Tensor 'concat_3:0' shape=(?, 3, ?, 1024) dtype=float32>}
```
while the output dictionary from `tf hub` contains:
- word_emb: the character-based word representations with shape [batch_size, max_length, 512].
- lstm_outputs1: the first LSTM hidden state with shape [batch_size, max_length, 1024].
- lstm_outputs2: the second LSTM hidden state with shape [batch_size, max_length, 1024].
- elmo: the weighted sum of the 3 layers, where the weights are trainable. This tensor has shape [batch_size, max_length, 1024]
- default: a fixed mean-pooling of all contextualized word representations with shape [batch_size, 1024].

how can I access the `word_emb, lstm_outputs1, lstm_outputs2 ..` fields in the output dictionary?
I am following the usage example to cache a dataset from [this link](https://github.com/allenai/bilm-tf/blob/master/bilm/model.py#L655)

**Comment by matt-peters** [comment]
lm_embeddings holds the embeddings for all layers, starting with word embeddings at the lowest layer.

```
word_emb = ops['lm_embeddings'][:, 0, :, :512]    # word embeddings are duplicated for forward/backward
lstm_outputs1 = ops['lm_embeddings'][:, 1, :, :]
lstm_outputs2 = ops['lm_embeddings'][:, 2, :, :]
```

**Comment by abd-ghreeb** [comment]
Thanks @matt-peters for the clarification, where is this info listed?
