### ISSUE TITLE
Checkpoint files for medium elmo model

### ISSUE THREAD

**Issue by abaheti95** [allenai/bilm-tf#198]
Sorry for opening a duplicate issue but the previous issue #105 was not resolved. @matt-peters, could you share the links to checkpoint of medium model as well. Simply changing the links in mentioned #105 gave "access denied" errors. Could you provide the correct checkpoint and vocab files links for this medium model?

**Comment by matt-peters** [comment]
It's here:
https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x2048_256_2048cnn_1xhighway/tf_checkpoint/options.json

https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x2048_256_2048cnn_1xhighway/tf_checkpoint/model.ckpt-1501260.meta

https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x2048_256_2048cnn_1xhighway/tf_checkpoint/model.ckpt-1501260.index

https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x2048_256_2048cnn_1xhighway/tf_checkpoint/model.ckpt-1501260.data-00000-of-00001

https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/vocab-2016-09-10.txt
