### ISSUE TITLE
max_batch_size issue

### ISSUE THREAD

**Issue by jackalhan** [allenai/bilm-tf#20]
Hi,

While I am trying to create embeddings for Questions like shown in usage_token.py, I am getting an error from the tensor because of having a different size than the max_batch_size?

How can I handle that case? Have you encountered such a problem in the project?

Thank you

**Comment by matt-peters** [comment]
The code will handle any batch size less than or equal to the max_batch_size.  If you want to use a larger batch then specify a different maximum when initializing the `BidirectionalLanguageModel` class.

**Comment by jackalhan** [comment]
Thank you
