### ISSUE TITLE
Contributed german ELMo model

### ISSUE THREAD

**Issue by PhilipMay** [allenai/bilm-tf#209]
I trained a germen ELMo model for german language (BSD-2-Clause) and would be happy if you could link it under "Contributed ELMo Models" maybe here: https://allennlp.org/elmo

Unlike most other ELMo models we also provide the checkpoint files for fine tuning.

Our german ELMo model GitHub Repo is here:
https://github.com/t-systems-on-site-services-gmbh/german-elmo-model

Thanks
Philip

**Comment by matt-peters** [comment]
Hi Philip,
Thank you for contributing this German model!!  Much appreciated.  I'm on holiday now but will be sure to add it to the contributed models page one back in the office (mid-August).

**Comment by PhilipMay** [comment]
Hi @matt-peters 
I hope you are fine after hollidays - I bet there is much to do.
I wanted to ask if you can (and want to) link to our german model.
Thanks
Philip

**Comment by matt-peters** [comment]
Hi @PhilipMay , I'll get a PR out for the website in the next few days.

**Comment by matt-peters** [comment]
@PhilipMay -- I have a PR open here to add a link for the German model: https://github.com/allenai/allennlp-website/pull/134

Would you please check the contributor information and let me know if you'd like to add any notes or links?  Thanks for your patience.

**Comment by PhilipMay** [comment]
Yes thanks. Maybe you could write “Philip May & T-Systems onsite” instead of just my name.

**Comment by matt-peters** [comment]
Updated, will merged soon.

**Comment by PhilipMay** [comment]
Thanks. :-)
