### ISSUE TITLE
The perplexity for bi-direction LM

### ISSUE THREAD

**Issue by jiangtongli** [allenai/bilm-tf#22]
In the paper, you said that the perplexity of the forward and backward lm is 39.6. Did you use golden word when you are validating the bi-lm?

**Comment by matt-peters** [comment]
The 39.6 value is the average of the forward and backward perplexities in the 1B Word benchmark held out set.  Each was computed in the standard way.

**Comment by jiangtongli** [comment]
Thanks，and what kind of words you use（correct or the predicted word） in the compute of bench perplexity？

**Comment by matt-peters** [comment]
Perplexity uses the predicted probability of the correct word and is computed as `exp(-1 / N * sum_k(ln(prob(w_k))))` for all words `w_k` in the held out set.  If you are unfamiliar with it then I recommend looking for a more detailed description elsewhere.
