### ISSUE TITLE
[ Question ] When does the inner state of the LSTMs reset during training?

### ISSUE THREAD

**Issue by tsteffek** [allenai/bilm-tf#220]
Just as a sanity check;
The shuffle_on_load flag made me believe, that the LSTMs' hidden state would be reset every sentence; however, diving into the code it seems it actually is not reset during entire training. Is this correct?

Might be a novice question, I'm new to Tensorflow I'm afraid.

**Comment by matt-peters** [comment]
That's correct, the LSTM hidden states are never reset during training.

**Comment by tsteffek** [comment]
Thanks for the quick answer.

Would you be interested in a PR adding a flag for document-wise training?

EDIT: Just had a talk with my boss again, seems like we're not doing that in the foreseeable future.
