### ISSUE TITLE
bug during data loading (and tests)

### ISSUE THREAD

**Issue by tsteffek** [allenai/bilm-tf#229]
I was fiddling around with the data loading (trying to get my own prefetching algorithm in there) when I realized something. According to your README, partial sentences and LSTM states are shared between batches, as well as within batches, as far as I can see.

Now, following this and given 3 sentences `['the unknown .', 'th .', 'the']` (straight from `test_data.py`) I would expect the sentences to be batched like this (with `unroll_steps=3, batch_size=2`):
<pre>
[
   [ '&lt;S>', 'the', 'unknown' ],      # [ 0, 3, 2 ]
   <b>[ '.', '&lt;S>', 'th' ],             # [ 4, 0, 2 ]</b>
]
[
   [ '.', '&lt;S>', 'the' ]             # [ 4, 0, 3 ]
   [ '&lt;S>', 'the', 'unknown' ],      # [ 0, 3, 2 ]
]
</pre>
(I omitted `</S>` since you remove it from the input as well.)

However, your code produces (and the tests verify) the following batches:
<pre>
[
   [ '&lt;S>', 'the', 'unknown' ],      # [ 0, 3, 2 ]
   <b>[ '&lt;S>', 'th', '.' ],             # [ 0, 2, 4 ]</b>
]
[
   [ '.', '&lt;S>', 'the' ]             # [ 4, 0, 3 ]
   [ '&lt;S>', 'the', 'unknown' ],      # [ 0, 3, 2 ]
]
</pre>

**The second sentence is wedged between the first half of the first sentence, and the second half.**

Now no matter whether the state is kept within the batch or not, this seems to produce a buggy input. Either it scrambles the state within the first sentence or drops the second sentence from the first batch's state.

Is this a plain old bug, or is there some deeper meaning to this?

**Comment by matt-peters** [comment]
Each row of the batches is treated independently by the model as one long sequence with separate states, they are not combined across rows in the batch.  As the sentences are shuffled during training, the model will learn to reset its internal state at each `<S>` so very little state is carried over from sentence to sentence, making this a non-issue in practice.  Also consider that in a real dataset, the number of sentences is typically much larger then the batch size, so repeating sentences across rows in the same batch rarely, if ever, occurs.

**Comment by tsteffek** [comment]
Ah, yes, I forgot that you guys shuffled the sentences. That changes things.
Thank you for your quick answer!
