### ISSUE TITLE
Is the small model used by the example codes trained on some corpus? Or is it some dummy model with randomly generated weights?

### ISSUE THREAD

**Issue by diaozh** [allenai/bilm-tf#23]
I am thinking of using Elmo in my project, but the model provided in the readme is too large for our application. Thanks!

**Comment by matt-peters** [comment]
The small model used in example code and the tests was trained on a tiny dataset (< 100 sentences) and should not be used for anything other then testing.  We plan to release smaller trained models in the future, but not until we can adequately benchmark their performance.
