### ISSUE TITLE
Pre-trained links do not work

### ISSUE THREAD

**Issue by eduamf** [allenai/bilm-tf#245]
Pre-trained links do not work. The tags are without address reference, like `<a>weight</a>`.

**Comment by danielshaps** [comment]
I am also unable to find links to the pre-trained models.

Are they available elsewhere?

**Comment by matt-peters** [comment]
The links seem to be working for me, can you provide more detail about which ones are broken?

**Comment by danielshaps** [comment]
The links to "weights" and "options" are empty for me (the anchor tags do not contain an href field -- as eduamf pointed out above) in the "Pre-trained ELMo Models" table on this page: https://allenai.org/allennlp/software/elmo

I'm using Firefox 107.0

**Comment by matt-peters** [comment]
Thanks for the heads up, we are on it!

**Comment by schmmd** [comment]
Yes, we will fix this.  Here is the HTML source for the ELMo site we migrated from if you would like a temporary work-around.

https://github.com/allenai/allennlp-website/blob/master/elmo.html

**Comment by danielshaps** [comment]
No problem, thank you for the link!

**Comment by jonborchardt** [comment]
pr: https://github.com/allenai/ai2-web/pull/1561
