### ISSUE TITLE
Which benchmark do you use in training elmo?

### ISSUE THREAD

**Issue by jiangtongli** [allenai/bilm-tf#25]
Sorry to bother again. I find there are two benchmarks in https://github.com/ciprian-chelba/1-billion-word-language-modeling-benchmark, the big one(9.9G) and the small one(1.7G). Would you like to tell me which benchmark do you use in training elmo.

**Comment by matt-peters** [comment]
I downloaded the data from http://www.statmt.org/lm-benchmark/

After expanding the tar ball, I used the all the files in the `training-monolingual.tokenized.shuffled` directory (approximately 3.9 GB decompressed).
