### ISSUE TITLE
Details about the training process.

### ISSUE THREAD

**Issue by jiangtongli** [allenai/bilm-tf#26]
I'm really sorry to broth you again. There are two ways to get the perplexity of your language model. (1) you input the really words in the sentence to the model and the model is going to predict the next word, which is called as training. (2) you input the word that the model just predict to the model and the model predict the next, which is called as inference.
So would you like to tell me, which way do you use in getting the perplexity of 39.4?
I'm not good at expressing my view in English and thanks for your patience!
By the way, would you like to tell me about the learning rate you use in training elmo?

**Comment by matt-peters** [comment]
Perplexity is computed using the method in (1).
I used Adagrad with learning rate = 0.2 to train the biLM.
