### ISSUE TITLE
How to provide heldout files to ELMo during training

### ISSUE THREAD

**Issue by wasiahmad** [allenai/bilm-tf#32]
It says to train ELMo on a new dataset, we need to provide a set of heldout files. But how? [Here](https://github.com/allenai/bilm-tf#2--train-the-bilm), using the command we can only provide the train files.

**Comment by matt-peters** [comment]
Use `bin/run_test.py` to evaluate the model.  See https://github.com/allenai/bilm-tf#3-evaluate-the-trained-model
