### ISSUE TITLE
Training does not end

### ISSUE THREAD

**Issue by wasiahmad** [allenai/bilm-tf#36]
I am training Elmo on a 30k sentence dataset for the last 24 hours and it is still not finished. The training perplexity is 2.12 for a while and it is not changing. I am also not sure what the output log means. I am getting something like this.

```
Batch 85900, train_perplexity=2.1179967
Total time: 87088.18443918228
Loading data from: ./data/elmo/small/data/part2.txt
Loaded 1014 sentences.
Finished loading
Loading data from: ./data/elmo/small/data/part1.txt
Loaded 29000 sentences.
Finished loading
Loading data from: ./data/elmo/small/data/part1.txt
Loaded 29000 sentences.
Finished loading
```

When the training is going to stop? Do I need to terminate training of my own?

Also, I have 2 files, part1.txt (for training) and part2.txt (for validation). I am not sure if Elmo is actually using part1 for training and part2 for validation. How can I ensure that?

**Comment by herbertchen1** [comment]
it's an RNN-based language model...with 2000(sentences)*700(file)*200(word/sentence) ,i got 1000000 batches , one epoch need 10 days to train with three 1080Ti................In fact ,i found the perpelexity become to 60 in batch 80000. Maybe it's enough.
I train with a chinese corpus . len(Vocabulary)=80*10000
