### ISSUE TITLE
Whether there is a memory leak in the training code

### ISSUE THREAD

**Issue by zsy23** [allenai/bilm-tf#37]
I run the training code, but memory usagel continues increasing until run out. My computer has 128G memory and total train files occupy only 1.3G in disk.

**Comment by matt-peters** [comment]
I haven't run into a memory leak but maybe you've hit an edge case.  Have you split your training data into many different files?  The training code loads each entire file into memory and converts to character ids so it's possible a 1.3 GB text file would expand to 128 GB of memory.

**Comment by zsy23** [comment]
Thank you for reply. I modify some part of code to train on chinese corpus, then run the code and find the code forever loop in the 'While True' loop in the bilm/data.py:_get_batch():line 263. Maybe because i modify some important detail, i will check it.
