### ISSUE TITLE
Using ELMo in SQuAD with spaCy tokenizing way

### ISSUE THREAD

**Issue by houyu0930** [allenai/bilm-tf#45]
Hi, I meet a problem about using ELMo with spaCy.

I use spaCy to preprocessing the text data, and without ELMo, the result looks fine. However, when I use the model with both spaCy and ELMo, I have gotten a very bad result, 0.08. There are many NAN and inf occurring when I see TensorFlow debugger. If I use NLTK and ELMo,  the result is what I expect. 

I think maybe there is something wrong when I using ELMo. However, when I saw the source code about ELMo, I didn't think there is relationship between ELMo and the tokenizing way(NLTK, spaCy). And I used the pre-training ELMo data for SQuAD. I've been plagued by this problem for a long time, I really want to know if it's something I missed. Is it necessary to train new ELMo data when I change into spaCy?

**Comment by houyu0930** [comment]
Have you met similar problems?

**Comment by matt-peters** [comment]
I haven't run into any problems when using different tokenizers.  I'd check the output from your tokenizing code to ensure tokens are python 3 strings and the proper data types (the batcher accepts input as lists of sentences, where each sentence is a list of tokens).
