### ISSUE TITLE
How long does it take to train the model?

### ISSUE THREAD

**Issue by mihirkale815** [allenai/bilm-tf#47]
How long does it take to train the model from the ELMO paper? I read that you used 3 GPUs. Which ones?
I want to get a rough idea before I can train my own.
This is not an issue per se, so if there's a different forum to discuss these things please let me know.

And congratulations on winning the best paper award at NAACL!

**Comment by matt-peters** [comment]
It took about 2 weeks.

**Comment by asiddhant** [comment]
I was running it on AWS EC2 p2.8xlarge on 8 GPUs and it was taking about 2.7 seconds per batch and for 10 epochs estimated time would be around 12 days.

**Comment by guotong1988** [comment]
THX
