### ISSUE TITLE
Question about the weight_layers

### ISSUE THREAD

**Issue by HuitingLiu** [allenai/bilm-tf#48]
Hi, thanks for the great paper and nice implementation. 

After reading through the paper and the code, I still feel confused about the weight_layers.

I saw that the dump_token_embeddings only return the intermediate LSTM status. It is not the final weighted ELMo vector. As mentioned in the paper, the weight_layers should be trained with the downstream task. However, in usage_token.py, the code directly creates the weight_layers and use it without training. Then, I was confused by the usage of the weight layers. Could you please explain it a little bit?  

Also, in the test_elmo.py, why is the expected_elmo calculated this way? I don't understand why the actual_elmo will be close to the values following these calculations. Could you please also explain it? 

Thanks a lot.

**Comment by matt-peters** [comment]
The usage of `weight_layers` is to apply the learned scalar average pooling to all of the layers from the model.  `dump_token_embeddings` will write out the embeddings from the first layer (context insensitive type layer) to a file, effectively caching the computation from the character CNN and highway layers for efficiency.  The usage files (e.g. `usage_token.py`) are intended to be templates to follow to compute the ELMo representations, for integrating with your downstream model.

**Comment by guotong1988** [comment]
Thank you very much.
