### ISSUE TITLE
Why are embeddings of feature length 1024? 

### ISSUE THREAD

**Issue by Sakib-Ar-Rahman** [allenai/bilm-tf#54]
(More of a question than an issue)
The embeddings are of shape (None, 3, None, 1024). Is there any specific reason why embeddings have a size of 1024? Which hyper parameter should I change if I want to reduce the embedding size?

**Comment by matt-peters** [comment]
This is 2X the output dimension from the forward and backward LMs.  This is `projection_dim ` in the hyperparameters.
