### ISSUE TITLE
no.of GPUs used for training  1 Billion Word Benchmark ?

### ISSUE THREAD

**Issue by kamalkraj** [allenai/bilm-tf#55]
I getting OOM with using single GTX 1080Ti

**Comment by Sakib-Ar-Rahman** [comment]
I believe the ELMo model was trained on three GPUs.

> The hyperparameters used to train the ELMo model can be found in bin/train_elmo.py.
> 
> The ELMo model was trained on 3 GPUs. To train a new model with the same hyperparameters, first download the training data from the 1 Billion Word Benchmark. Then download the vocabulary file...

[link to README section](https://github.com/allenai/bilm-tf#2--train-the-bilm)

**Comment by kamalkraj** [comment]
Which 3 GPUs ? GTX 1080 ?

**Comment by matt-peters** [comment]
The original ELMo model was trained on 3 GTX 1080's.

**Comment by svjan5** [comment]
Hi, can you share how much time it took for you to train the entire model?

**Comment by matt-peters** [comment]
It took about two weeks for 10 epochs.

**Comment by svjan5** [comment]
Thanks!
