### ISSUE TITLE
Code loads only two of the data shards while training. 

### ISSUE THREAD

**Issue by ashim95** [allenai/bilm-tf#56]
I have a gigantic dataset to train Elmo on. So I split the training set into 1000 separate files. While loading data for training I see that only two of the files are loaded (reverse=True and False). Why is that? Or Am I missing something?

And btw Congratulations on winning the best paper award at NAACL!

Thanks,

**Comment by matt-peters** [comment]
This is normal, training only loads one file at a time in each direction, then moves on to the next random file after exhausting the first.  Does training eventually load another file, or just reload the first file again?

**Comment by matt-peters** [comment]
The criteria for stopping is specified by the number of tokens in the training data, the number of epochs, and the batch size.  All of these are specified in the training options: https://github.com/allenai/bilm-tf/blob/master/bin/train_elmo.py
