### ISSUE TITLE
Generate ELMO from Glove

### ISSUE THREAD

**Issue by MariamEssam** [allenai/bilm-tf#58]
I have a model that performs sentiment analysis task and that uses Glove as word embedding, in the beginning, I load the Glove file glove.xxxB.yyyd.txt(xxx---token,yyy---dimension). Now I need instead of that to load the ELMO file that's equivalent to this glove. In another word, I need to map between Glove and ELMO one to one mapping is that possible? And if that possible what's the exported dimension of ELMO?

**Comment by zxgineng** [comment]
I think ELMO is contextualized. Same word in different sentences maps different vec in ELMO, whille Glove maps one fixed vec in all sentences. They are totally diffenrent.

**Comment by MariamEssam** [comment]
@zxgineng  so if I need to replace Glove I have to use the dataset direct to generate a vector per token not to look in the glove file and find the equivalent vector correct?
In other words, in glove we use the data set tokens and check for each token to the equivalent word in glove file and take the corresponding vector if found.
Now instead of looking inside glove file, we are going to generate for each token an ELMO vector.
Correct? If yes before per token we have 300d vector in ELMO what's the dimensionality?

**Comment by matt-peters** [comment]
"Now instead of looking inside glove file, we are going to generate for each token an ELMO vector.
Correct?" -- Yes, this is correct.  You will compute an ELMo vector for each token in your input sentence.

"If yes before per token we have 300d vector in ELMO what's the dimensionality?"  -- for the provided pre-trained model, it's 1024.

**Comment by peppe69** [comment]
> for the provided pre-trained model, it's 1024.

So, the pretrained model is a plug-and-play one, just like GloVe? Or we need to train it too in the current context?
