### ISSUE TITLE
loss calculation

### ISSUE THREAD

**Issue by mehdimashayekhi** [allenai/bilm-tf#65]
why the loss is multiplied by "unroll steps " here? https://github.com/allenai/bilm-tf/blob/81a4b54937f4dfb93308f709c1cf34dbb37c553e/bilm/training.py#L705. wasn't the effect of loss, taken into account when it was calculated originally here? https://github.com/allenai/bilm-tf/blob/81a4b54937f4dfb93308f709c1cf34dbb37c553e/bilm/training.py#L427, reason being is, the second dimension of next token id is equal to unroll step defined here :https://github.com/allenai/bilm-tf/blob/81a4b54937f4dfb93308f709c1cf34dbb37c553e/bilm/training.py#L441

**Comment by matt-peters** [comment]
Multiplying by `unroll_steps` here effectively scales the loss so that we are summing over each token in the batch.
