### ISSUE TITLE
Hub version to train new embedding

### ISSUE THREAD

**Issue by buptcjj** [allenai/bilm-tf#68]
May I use hub version from tensorflow to train my own elmo embedding? And my corpus is Chinese.
If it's OK , can you give me a simple example?
Thank you so much.

**Comment by qujinqiang** [comment]
@buptcjj 你是训练字向量用的吗？ 我想直接用官方提供的docker镜像应该更方便些

**Comment by qujinqiang** [comment]
@buptcjj 这个是字符级别的输入，我想问下用来训练中文字向量可行吗？

**Comment by matt-peters** [comment]
The hub version only provides the pre-trained model and can't be used for training.
To train your own model, use the code in this repository, see the README.md.
