### ISSUE TITLE
What's the relationship of "BidirectionalLanguageModel"  and "LanguageModel"?

### ISSUE THREAD

**Issue by leon-cas** [allenai/bilm-tf#69]
And in train_elmo.py , it use "LanguageModel".  But in usage_character.py and usage_token.py, the "BidirectionalLanguageModel" class is used.

so, what's the relationship of class "BidirectionalLanguageModel" in bilm/model.py and class "LanguageModel" in bilm/training.py?  thanks

**Comment by matt-peters** [comment]
`BidirectionalLanguageModel` is used to compute embeddings with a trained model (so doesn't have ability to compute the loss, etc).  `LanguageModel` is used for training.

**Comment by leon-cas** [comment]
ok, thanks @matt-peters .
