### ISSUE TITLE
LSTM final states as the initial states of next batch

### ISSUE THREAD

**Issue by goncalomcorreia** [allenai/bilm-tf#74]
Hi!

It seems to me from the code provided that the final states of each batch are fed as the initial states of the next batch. However, in `data.py` the examples in a batch seem to be the continuation of the previous example in the same batch (when the sentence is greater than the BPTT rollout steps). If what I'm saying is correct, we are feeding the final states to a new batch that is not the continuation of the sentences in the previous batch.

Why is that so? What am I missing?

**Comment by matt-peters** [comment]
In prediction, we are making the assumption that each row in each batch contains a full sentence (and indeed, the batchers will add the special `<S>` and `</S>` tokens).
