### ISSUE TITLE
a strange error occurred

### ISSUE THREAD

**Issue by goingcoder** [allenai/bilm-tf#76]
**'ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [16384] and type float'**

I modified the code of train_elmo.py like this:

options = {
     'bidirectional': True,

     # 'char_cnn': {'activation': 'relu',
     #  'embedding': {'dim': 16},
     #  'filters': [[1, 32],
     #   [2, 32],
     #   [3, 64],
     #   [4, 128],
     #   [5, 256],
     #   [6, 512],
     #   [7, 1024]],
     #  'max_characters_per_token': 50,
     #  'n_characters': 6707,
     #  'n_highway': 2},

**Cause I want to run this code only based on word_emb without char_emb
Then this  error called 'ResourceExhaustedError' occurred
Could you tell me how to fix that?
THX !!!**

**Comment by matt-peters** [comment]
This modification will use word embeddings for the input instead of the character CNN, and therefore significantly increase the amount of GPU memory used.  You can fix it by some combination of (1) more GPU memory (2) smaller batch size (3) smaller model size or (4) smaller vocabulary.
