### ISSUE TITLE
warning when training my own corpus

### ISSUE THREAD

**Issue by linzehui** [allenai/bilm-tf#78]
I use the train code to train my Chinese corpus like this:
![image](https://user-images.githubusercontent.com/16056955/43812675-e900c356-9af4-11e8-9391-3e231f0fc82d.png)

I have provided corpus and vocabulary files as the Readme said. While the training process continued, some warning/error occured:
>'list' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing lstm_output_embeddings.
Type is unsupported, or the types of the items don't match field type in CollectionDef.

![image](https://user-images.githubusercontent.com/16056955/43812798-9209724a-9af5-11e8-8bfe-a7708f33d5e3.png)

Although the process did not terminate, after 4 days of training, the hdf5 files didn't show up as expected. I searched on google but no clue.

Any idea on this error? Thanks!!!

**Comment by felixwzh** [comment]
Maybe you should run [this](https://github.com/allenai/bilm-tf#4-convert-the-tensorflow-checkpoint-to-hdf5-for-prediction-with-bilm-or-allennlp) to generate the hdf5 file?

**Comment by linzehui** [comment]
thanks !!! I did't notice that 😅
