### ISSUE TITLE
Can the program only run on gpu

### ISSUE THREAD

**Issue by zheyang0715** [allenai/bilm-tf#81]
Can the program only run on gpu？Can it run on Windows

**Comment by hclent** [comment]
I was able to successfully *start* training it on a machine without a gpu surprisingly (I set `n_gpus = 1` in `train_elmo.py`). However I ended up killing it and moving over to a machine with gpus after I got it working on my personal machine, so I cannot say for sure whether it would have failed or succeeded in the long run. I do not believe you are supposed to be able to run it without a gpu, based on the Docker container that they provide. That said, if you do go ahead and try to run it on your gpu-less machine, here's a snippit of the warnings and errors you can expect to see in the early stages of training: 

```
...
WARNING:tensorflow:From /anaconda3/envs/n2c2/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:107: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2018-08-19 17:01:37.153456: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
WARNING:tensorflow:Error encountered when serializing lstm_output_embeddings.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'list' object has no attribute 'name'
Training for 1 epochs and 360433 batches
Batch 100, train_perplexity=10765.455
Total time: 308.85043811798096
Batch 200, train_perplexity=4832.25
Total time: 595.8428201675415
Batch 300, train_perplexity=2711.2388
Total time: 872.3275389671326
Batch 400, train_perplexity=906.73627
Total time: 1521.434888124466
Batch 500, train_perplexity=495.6229
...
```

I've been able to successfully run it on *nix. To test if you can run on Windows, I'd suggest running the test they provide you in the README :)

**Comment by matt-peters** [comment]
Yes, it will run fine, just slowly, on CPU.

I haven't tried to install on windows, but since tensorflow runs on Windows you should be able to get it working.
