### ISSUE TITLE
Architecture of BiLSTM

### ISSUE THREAD

**Issue by leerumor** [allenai/bilm-tf#84]
I'm a beginner and a little confused about the implementation of BiLSTM, in my point of view, the bilstm for a language model is different from a standard bilstm (see this: https://github.com/dongjun-Lee/birnn-language-model-tf). But in LanguageModel and BidirectionalLanguageModel, i think the bilstm is just the standard one?
What's more, in BidirectionalLanguageModel, when 'direction=backward', both the input and output are reversed, but in LanguageModel, only the input are reversed, am i missing some thing?

**Comment by matt-peters** [comment]
Each direction of the LM makes independent predictions.

During training, we have different forward and backward sentences, while for prediction we only have one sentence and run both the forward and backward LSTMs on the single sentence.
