### ISSUE TITLE
The "unroll_steps" when evaluating the trained model

### ISSUE THREAD

**Issue by FynnYoung** [allenai/bilm-tf#85]
Hello,
I notice that the parameter "unroll_steps" is set to be 1 when using "run_test.py" to evaluate the model. Why not use the whole sentence to compute the perplexity?

**Comment by matt-peters** [comment]
The whole sentence is used for computing the average perplexity, subsequent tokens are used in the subsequent batches.

Testing uses significantly more GPU memory then training as it uses the full softmax (training uses a sampled softmax).  As a result, we use `unroll_steps` = 1 during testing to avoid running out of memory.
