### ISSUE TITLE
Preprocessing steps for training ELMO 

### ISSUE THREAD

**Issue by iamyihwa** [allenai/bilm-tf#86]
Hello, 

I was wondering if the preprocessing steps for training ELMO is specific to ELMO or applies in general to AllenNLP in general? 
The part I am referring to are below part in the README.md. 
```The training data should be randomly split into many training files, each containing one slice of the data. Each file contains pre-tokenized and white space separated text, one sentence per line. Don't include the <S> or </S> tokens in your training data.

All tokenization/normalization is done before training a model, so both the vocabulary file and training files should include normalized tokens. As the default settings use a fully character based token representation, in general we do not recommend any normalization other then tokenization.```

Just to be clear ..

**Comment by matt-peters** [comment]
For using the existing pre-trained models with this library or allennlp, don't apply any pre-processing other then tokenization.

For training your own models, you can use whatever pre-processing you want, as long as you are consistent when both training and predicting.
