### ISSUE TITLE
training file format 

### ISSUE THREAD

**Issue by iamyihwa** [allenai/bilm-tf#87]
Hello 

I find below lines a bit confusing. 

> The training data should be randomly split into many training files, each containing one slice of the data. **Each file contains pre-tokenized and white space separated text,** one sentence per line. Don't include the <S> or </S> tokens in your training data.
> 
> All tokenization/normalization is done before training a model, so both the vocabulary file and **training files should include normalized tokens.** As the default settings use a fully character based token representation, in general we do not recommend any normalization other then tokenization.
> 

What should the file be like ? 
e.g. 
Original sentence: 
Allen Institute is located in Seattle, US. 

(1) 
Training Data: 
allen institute is located in seattle , us . 

(2) 
Training Data: 
Allen Institute is located in Seattle, US. 

(1) or (2)???

**Comment by matt-peters** [comment]
The file should be tokenized, but in general we don't recommend lower casing.  So the file should include a line like this, assuming the tokenizer splits commas and periods from the previous token:

```
Allen Institute is located in Seattle , US .
```

**Comment by iamyihwa** [comment]
Thanks !

**Comment by sathiyabalu89** [comment]
How do I prepare the training data if I have many multi word token in domain like chemistry. For example: 

**1. Original Sentences:**: "This is a multi word chemical component 3-(4,5-dimethylthiazol-2-yl)-2,5-diphenyl tetrazolium bromide. \n This is another sentence."

Here "3-(4,5-dimethylthiazol-2-yl)-2,5-diphenyl tetrazolium bromide" is a single token. There are multiple words inside the token which are white space separated. This would lead to the above token to be split as 3 tokens: ['3-(4,5-dimethylthiazol-2-yl)-2,5-diphenyl','tetrazolium', 'bromide'].

How can I avoid this? Can I give the input training data in the following format to avoid this?

**Training data(1)** : List of tokens for each sentences. So the training text file will have list of list tokens.

 [['This', 'is', 'a', 'multi', 'word', 'chemical', 'component', '3-(4,5-dimethylthiazol-2-yl)-2,5-diphenyl tetrazolium bromide'], ['This', 'is', 'another', 'sentence.']]

** Training data(2)** : "This is a multi word chemical component 3-(4,5-dimethylthiazol-2-yl)-2,5-diphenyl|tetrazolium|bromide.  \n This is another sentence."

Please guide on the best way to prepare the training data.
