### ISSUE TITLE
error when training ELMO 

### ISSUE THREAD

**Issue by iamyihwa** [allenai/bilm-tf#90]
Hello, 

I am trying to train ELMO. 

The test have all been passed. 
![image](https://user-images.githubusercontent.com/12494156/44854502-fdd57080-ac68-11e8-8e8d-4a9fc172cd4d.png)

I have used following script to train, as was described in [here](https://github.com/allenai/bilm-tf). 
![image](https://user-images.githubusercontent.com/12494156/44854553-265d6a80-ac69-11e8-86a0-727c9727d095.png)

However I get an error 
: UnboundLocalError: local variable 'k' referenced before assignment
(Image attached)
![image](https://user-images.githubusercontent.com/12494156/44854470-e72f1980-ac68-11e8-9d24-96a9694d9815.png)

**Comment by palcery** [comment]
You can simply avoid this error by editing the code bilm/data.py as follows, somewhat inefficient though.

```python
        for k, chr_id in enumerate(word_encoded, start=1):
            code[k] = chr_id
            code[k + 1] = self.eow_char
```

**Comment by iamyihwa** [comment]
@jinsik-lee 
Did the suggestion, however get the same error.. 
![image](https://user-images.githubusercontent.com/12494156/44971417-c9f29780-af55-11e8-85f5-9406425e06d8.png)

**Comment by iamyihwa** [comment]
@jinsik-lee thanks it worked! Sorry i was using pip installed version, so the local change was not reflected. After reinstalling it with 'pip install -e ' option it worked!
