### ISSUE TITLE
I created and uploaded a PyPI package of bilm.

### ISSUE THREAD

**Issue by PhilipMay** [allenai/bilm-tf#93]
Hi,
I just wanted to let you know that I created and uploaded a PyPI package of bilm. See here: https://pypi.org/project/bilm/
I did set myself as maintainer and offer to maintain it if you want me to.
I also plan to create a conda package for conda-forge: https://conda-forge.org/

Otherwise if you want I can transfer the package in PyPI (and the maintainer attribute) to you.

Thanks
Philip

**Comment by matt-peters** [comment]
Thank you!
In the long run it's probably best if we maintain the packages -- will follow up via email.

**Comment by PhilipMay** [comment]
I added mattpeters as additional owner on PyPI:
https://pypi.org/manage/project/bilm/collaboration/

**Comment by matt-peters** [comment]
Thanks Philip!
