### ISSUE TITLE
Number of tokens in training data greatly affects RAM usage

### ISSUE THREAD

**Issue by mathetes87** [allenai/bilm-tf#97]
Hi, 

First of all, thank you for your continuous support to this repository. It helps a ton in using ELMO as a building block.

I have a question regarding the memory usage of the parameter `n_train_tokens` in the `train_elmo.py` parameters file when training a new model from scratch. 

I tried to use a rather small dataset with the built in parameters but I kept having problems with the RAM usage: my dictionary has ~17,000 unique tokens and my initial train dataset has ~450,000 lines in a single file (I trimmed down to 50 lines but kept having the same issue).

The problems with the memory usage seem to go away when I change the `n_train_tokens` parameter. First I had it untouched from the default `768648884`, and when I changed it to my `4527840` tokens in the train corpus, it started to train just fine. 

The thing is that I could not trace the reason for this change in the RAM usage within the code. The parameter seems to only affect the number of total batches for the model to train... how is that related to memory usage within the GPU??

I have a GTX1070 with 8GB of RAM.

Thanks a lot

**Comment by matt-peters** [comment]
As you said, `n_train_tokens` doesn't have any relationship to GPU usage, it only determines the number of batches to run, with larger values training for more batches.  So there must be another problem elsewhere.   It's possible you have a memory leak and larger `n_train_tokens` trains for longer thus crashing? In the case where it runs out of memory, does GPU usage slowly increase until OOM?

**Comment by mathetes87** [comment]
The memory usage increases abruptly and then kind of oscillates, at least when it is small enough to fit in memory. The problem arises as soon as training starts, if I crank the number up, I'm not able to process a single batch before it crashes.

I'll dig deeper into the issue and report back. Thanks for the help

**Comment by mathetes87** [comment]
Ok, there must have been something else messing with my RAM... I can't reproduce the issue anymore. 

I do have problems when using the default settings for the original model as described [here](https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json). However, after setting the `config.gpu_options.allow_growth = True` for the `Session` I can successfully train the model. I got the idea from [here](https://stackoverflow.com/questions/36927607/how-can-i-solve-ran-out-of-gpu-memory-in-tensorflow)

Thank you for your help
