### ISSUE TITLE
How to train the code on CPU

### ISSUE THREAD

**Issue by sandhiya18** [allenai/bilm-tf#98]
I am trying to do a transfer learning using bilm-tf on CPU .  What are the code changes required for performing the experiment on CPU?

**Comment by matt-peters** [comment]
To use CPU, set `n_gpus=1` in your options (internally this just means one model replica) and mask out the GPUs by setting the environmental variable `CUDA_VISIBLE_DEVICES` to empty:
```
export CUDA_VISIBLE_DEVICES=
```
Then the code should run fine, just slow.  If you have tensorflow-gpu installed it may complain that a GPU doesn't exist but you can ignore the warnings.
